version: '3.8'

services:
  mocker_db:
    image: mongo:4.2.0-bionic
    container_name: mocker_db
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - DATABASE_PORT=${DATABASE_PORT}
    volumes:
      - mocker_db:/data/db

  mocker:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: mocker
    container_name: mocker
    image: mocker:latest
    restart: always
    ports:
      - "SERVER_PORT:SERVER_PORT"
    environment:
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - .:/app


volumes:
  mocker_db:
