version: '3.8'

services:
  mocker_db:
    image: mongo:4.2.0-bionic
    container_name: mocker_db
    ports:
      - 27017:27017
    environment:
      - DATABASE_PORT=27017
    volumes:
      - mocker_db:/data/db
    command: mongod --port 27017

volumes:
  mocker_db: