version: '3.8'

services:
  mocker_db:
    image: mongo:4.2.0-bionic
    container_name: mocker_db
    ports:
      - 27018:27017
    volumes:
      - mocker_db:/data/db

  mocker:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: mocker
    container_name: mocker
    image: mocker:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app


volumes:
  mocker_db:
