version: '3.4'

services:
  server:
    build:
      context: .
    container_name: server
    depends_on:
      - mongodb
      - redis
    ports:
      - 3000:3000
    environment:
      SERVER_PORT: 3000
      DB_URL: mongodb://mongodb:27017/mocker
      UPLOADPATH: ./uploads
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CLIENT_URL: http://client:8080
      SECRET: f002e557ad00ee5e328b719efe44fd9054933475585bbc1b42d5ec1278862df2

  client:
    build: 
      context: ./web
    container_name: client
    ports:
      - 8080:8080
    environment:
      - CLIENT_PORT=8080
      - SERVER_PORT=3000
      - SERVER_HOST=server

  mongodb:
    image: mongo:4.2.0-bionic
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:

